# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2019.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/aeryz/Downloads/Telegram Desktop/ztp-core"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/aeryz/Downloads/Telegram Desktop/ztp-core"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/clion-2019.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/aeryz/Downloads/Telegram Desktop/ztp-core/CMakeFiles" "/home/aeryz/Downloads/Telegram Desktop/ztp-core/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/aeryz/Downloads/Telegram Desktop/ztp-core/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ztp

# Build rule for target.
ztp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ztp
.PHONY : ztp

# fast build rule for target.
ztp/fast:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/build
.PHONY : ztp/fast

modules/local_security.o: modules/local_security.cpp.o

.PHONY : modules/local_security.o

# target to build an object file
modules/local_security.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/modules/local_security.cpp.o
.PHONY : modules/local_security.cpp.o

modules/local_security.i: modules/local_security.cpp.i

.PHONY : modules/local_security.i

# target to preprocess a source file
modules/local_security.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/modules/local_security.cpp.i
.PHONY : modules/local_security.cpp.i

modules/local_security.s: modules/local_security.cpp.s

.PHONY : modules/local_security.s

# target to generate assembly for a file
modules/local_security.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/modules/local_security.cpp.s
.PHONY : modules/local_security.cpp.s

modules/windows_local_security.o: modules/windows_local_security.cpp.o

.PHONY : modules/windows_local_security.o

# target to build an object file
modules/windows_local_security.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/modules/windows_local_security.cpp.o
.PHONY : modules/windows_local_security.cpp.o

modules/windows_local_security.i: modules/windows_local_security.cpp.i

.PHONY : modules/windows_local_security.i

# target to preprocess a source file
modules/windows_local_security.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/modules/windows_local_security.cpp.i
.PHONY : modules/windows_local_security.cpp.i

modules/windows_local_security.s: modules/windows_local_security.cpp.s

.PHONY : modules/windows_local_security.s

# target to generate assembly for a file
modules/windows_local_security.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/modules/windows_local_security.cpp.s
.PHONY : modules/windows_local_security.cpp.s

src/alive_test.o: src/alive_test.cpp.o

.PHONY : src/alive_test.o

# target to build an object file
src/alive_test.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/alive_test.cpp.o
.PHONY : src/alive_test.cpp.o

src/alive_test.i: src/alive_test.cpp.i

.PHONY : src/alive_test.i

# target to preprocess a source file
src/alive_test.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/alive_test.cpp.i
.PHONY : src/alive_test.cpp.i

src/alive_test.s: src/alive_test.cpp.s

.PHONY : src/alive_test.s

# target to generate assembly for a file
src/alive_test.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/alive_test.cpp.s
.PHONY : src/alive_test.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/database_ctrl.o: src/database_ctrl.cpp.o

.PHONY : src/database_ctrl.o

# target to build an object file
src/database_ctrl.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/database_ctrl.cpp.o
.PHONY : src/database_ctrl.cpp.o

src/database_ctrl.i: src/database_ctrl.cpp.i

.PHONY : src/database_ctrl.i

# target to preprocess a source file
src/database_ctrl.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/database_ctrl.cpp.i
.PHONY : src/database_ctrl.cpp.i

src/database_ctrl.s: src/database_ctrl.cpp.s

.PHONY : src/database_ctrl.s

# target to generate assembly for a file
src/database_ctrl.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/database_ctrl.cpp.s
.PHONY : src/database_ctrl.cpp.s

src/helper.o: src/helper.cpp.o

.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i

.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s

.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/os_finder_ssh.o: src/os_finder_ssh.cpp.o

.PHONY : src/os_finder_ssh.o

# target to build an object file
src/os_finder_ssh.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/os_finder_ssh.cpp.o
.PHONY : src/os_finder_ssh.cpp.o

src/os_finder_ssh.i: src/os_finder_ssh.cpp.i

.PHONY : src/os_finder_ssh.i

# target to preprocess a source file
src/os_finder_ssh.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/os_finder_ssh.cpp.i
.PHONY : src/os_finder_ssh.cpp.i

src/os_finder_ssh.s: src/os_finder_ssh.cpp.s

.PHONY : src/os_finder_ssh.s

# target to generate assembly for a file
src/os_finder_ssh.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/os_finder_ssh.cpp.s
.PHONY : src/os_finder_ssh.cpp.s

src/ssh_client.o: src/ssh_client.cpp.o

.PHONY : src/ssh_client.o

# target to build an object file
src/ssh_client.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/ssh_client.cpp.o
.PHONY : src/ssh_client.cpp.o

src/ssh_client.i: src/ssh_client.cpp.i

.PHONY : src/ssh_client.i

# target to preprocess a source file
src/ssh_client.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/ssh_client.cpp.i
.PHONY : src/ssh_client.cpp.i

src/ssh_client.s: src/ssh_client.cpp.s

.PHONY : src/ssh_client.s

# target to generate assembly for a file
src/ssh_client.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/ssh_client.cpp.s
.PHONY : src/ssh_client.cpp.s

src/vendor/easylogging++/easylogging++.o: src/vendor/easylogging++/easylogging++.cpp.o

.PHONY : src/vendor/easylogging++/easylogging++.o

# target to build an object file
src/vendor/easylogging++/easylogging++.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/vendor/easylogging++/easylogging++.cpp.o
.PHONY : src/vendor/easylogging++/easylogging++.cpp.o

src/vendor/easylogging++/easylogging++.i: src/vendor/easylogging++/easylogging++.cpp.i

.PHONY : src/vendor/easylogging++/easylogging++.i

# target to preprocess a source file
src/vendor/easylogging++/easylogging++.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/vendor/easylogging++/easylogging++.cpp.i
.PHONY : src/vendor/easylogging++/easylogging++.cpp.i

src/vendor/easylogging++/easylogging++.s: src/vendor/easylogging++/easylogging++.cpp.s

.PHONY : src/vendor/easylogging++/easylogging++.s

# target to generate assembly for a file
src/vendor/easylogging++/easylogging++.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/vendor/easylogging++/easylogging++.cpp.s
.PHONY : src/vendor/easylogging++/easylogging++.cpp.s

src/version_ops.o: src/version_ops.cpp.o

.PHONY : src/version_ops.o

# target to build an object file
src/version_ops.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/version_ops.cpp.o
.PHONY : src/version_ops.cpp.o

src/version_ops.i: src/version_ops.cpp.i

.PHONY : src/version_ops.i

# target to preprocess a source file
src/version_ops.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/version_ops.cpp.i
.PHONY : src/version_ops.cpp.i

src/version_ops.s: src/version_ops.cpp.s

.PHONY : src/version_ops.s

# target to generate assembly for a file
src/version_ops.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/version_ops.cpp.s
.PHONY : src/version_ops.cpp.s

src/windows_commands.o: src/windows_commands.cpp.o

.PHONY : src/windows_commands.o

# target to build an object file
src/windows_commands.cpp.o:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/windows_commands.cpp.o
.PHONY : src/windows_commands.cpp.o

src/windows_commands.i: src/windows_commands.cpp.i

.PHONY : src/windows_commands.i

# target to preprocess a source file
src/windows_commands.cpp.i:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/windows_commands.cpp.i
.PHONY : src/windows_commands.cpp.i

src/windows_commands.s: src/windows_commands.cpp.s

.PHONY : src/windows_commands.s

# target to generate assembly for a file
src/windows_commands.cpp.s:
	$(MAKE) -f CMakeFiles/ztp.dir/build.make CMakeFiles/ztp.dir/src/windows_commands.cpp.s
.PHONY : src/windows_commands.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... ztp"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... modules/local_security.o"
	@echo "... modules/local_security.i"
	@echo "... modules/local_security.s"
	@echo "... modules/windows_local_security.o"
	@echo "... modules/windows_local_security.i"
	@echo "... modules/windows_local_security.s"
	@echo "... src/alive_test.o"
	@echo "... src/alive_test.i"
	@echo "... src/alive_test.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/database_ctrl.o"
	@echo "... src/database_ctrl.i"
	@echo "... src/database_ctrl.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/os_finder_ssh.o"
	@echo "... src/os_finder_ssh.i"
	@echo "... src/os_finder_ssh.s"
	@echo "... src/ssh_client.o"
	@echo "... src/ssh_client.i"
	@echo "... src/ssh_client.s"
	@echo "... src/vendor/easylogging++/easylogging++.o"
	@echo "... src/vendor/easylogging++/easylogging++.i"
	@echo "... src/vendor/easylogging++/easylogging++.s"
	@echo "... src/version_ops.o"
	@echo "... src/version_ops.i"
	@echo "... src/version_ops.s"
	@echo "... src/windows_commands.o"
	@echo "... src/windows_commands.i"
	@echo "... src/windows_commands.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

